### ISSUE TITLE
Feature Request: Provide prebuilt binaries for mdbook-admonish

### ISSUE THREAD

**Issue by bgianfo** [tommilligan/mdbook-admonish#13]
Many other mdbook preprocessors provide prebuilt binaries. This helps to enable the use of  preprocessors in automation scenarios.

For example I'm interested in using `mdbook-admonish` with the `actions-mdbook` github action. It currently requires prebuilt binaries, more details here: https://github.com/peaceiris/actions-mdbook/issues/426#issuecomment-1102752476

Would you be willing to provide prebuilt binaries for `mdbook-admonish`?

It looks like you could probably just modify the existing actions workflow that `mdboom-mermaid` uses: https://github.com/badboy/mdbook-mermaid/blob/main/.github/workflows/deploy.yml

**Comment by tommilligan** [comment]
Hi, thanks for the feature request!

That sounds very doable. I will look into integrating the workflow as you suggest. I have a busy couple of days but should be able to look into it at the weekend. Feel free to ping me on it if you haven't heard anything in a week :slightly_smiling_face:

**Comment by schungx** [comment]
I wonder if pre-built binaries can also be packaged into `crates.io`?

**Comment by tommilligan** [comment]
I don't believe crates.io supports binary installs natively, as [cargo-binstall exists](https://crates.io/crates/cargo-binstall).

I've ~stolen~ adapted the workflow you suggested @bgianfo, and cut a new patch version with the artefacts here: https://github.com/tommilligan/mdbook-admonish/releases/tag/v1.4.1

If that fits your use case I think we can consider this closed, if not please let me know what's missing :slightly_smiling_face:

**Comment by bgianfo** [comment]
🥳 Exactly what I was hoping for, thank you @tommilligan, really appreciate it!
