### ISSUE TITLE
Add ID from title

### ISSUE THREAD

**Issue by schungx** [tommilligan/mdbook-admonish#15]
It would be good to have, say, the following:

~~~
```admonish tip "Hello"
...
```
~~~

to generate a `div` with an `id` (like for MarkDown titles) that comes from the title:

```html
<div class="admonition-title" id="hello">
```

This way it is possible to refer to this admonition in a URL link.

**Comment by tommilligan** [comment]
Good suggestion - I recently updated the code for this in `mdbook` itself actually, so pretty sure I can just pull that logic in.

**Comment by tommilligan** [comment]
Released in https://github.com/tommilligan/mdbook-admonish/releases/tag/v1.5.0
