### ISSUE TITLE
While converting the book to pdf, the admonish blocks are not rendered properly.

### ISSUE THREAD

**Issue by csk111165** [tommilligan/mdbook-admonish#151]
Hi  @tommilligan,

Good morning.
I tried to use the admonish block for creating the mdbook and tried to convert the book to pdf using below two options:

- Using Ctrl+P in chrome
- Using mdbook-pdf tool

But both the method yielded in not getting the proper formatted block.

Could you please help @tommilligan 

### PDF output 

![image](https://github.com/tommilligan/mdbook-admonish/assets/10927010/3b0a41ab-734c-4a0d-a61a-a66cb76d6ec1)

**Comment by tommilligan** [comment]
Hi, thanks for reporting this issue. Agreed that from your screenshot the rendering looks different than in browser.

I'm guessing we can investigate CSS/HTML that renders better both in the browser and in PDF printing. I'm not aware of how mdbook-pdf works - I guess looking at the rendering engine there might give some hints. It may just be that we need to transpile/fallback a bunch of the CSS to target the renderer?

This isn't something I'm particularly interested in doing myself. I'm very open to PRs and reviewing anything you come up with though.

**Comment by csk111165** [comment]
Thanks @tommilligan for acknowledging the same, as mentioned above that I used browser's inbuilt functionality of converting the html to pdf using `ctrl+p` (in windows) but again the result were same as converting it into pdf using `mdbook-pdf`.
I would have loved to contribute to this fix but my technical expertise restricts me from raising a PR as I am now well versed with front end side.
I request you to please provide a fix as it is important in many case.
- It will allow the use to publish the book in pdf format and people where the internet is not accessible can also use the book offline.
- It would allow a better readability and provide a great user reading experience.
- It would encourage, author like me to fully rely on admonish to allow styling in the page ( as other platform induces a plenty of charge like gitbook)

Please do consider the request, Thank you :)

**Comment by tommilligan** [comment]
You can try the fix for this out locally with

```bash
cargo install --git https://github.com/tommilligan/mdbook-admonish --branch main
```

It will also be included in the next release. Let me know any other feedback you have!
