### ISSUE TITLE
TLDR admonish rendering

### ISSUE THREAD

**Issue by joshka** [tommilligan/mdbook-admonish#153]
Right now the tldr admonishment renders as `Tldr`. It would be nice if this would render as `TL;DR` instead.

**Comment by tommilligan** [comment]
As you can achieve the desired output simply with

````markdown
```admonish title="TL;DR"
The following steps can lead to irrecoverable data corruption.
```
````

I don't think this is worth adding a special case for. There's also multiple stylings of this (`TL;DR`, `tldr`, `tl;dr`), so it's not clear to me which one we'd implement.

---

I think architecturally, maybe this would be something to add when supporting multiple languages. If you really did want to add it, I think the right way to do so would be with a localization framework in mind; something like `locale = en_US`, and then we map to correct default titles for english, chinese, etc.

The other directive that sticks out to me as benefiting from this treatment is `faq`.

**Comment by joshka** [comment]
`admonish title="TL;DR"` makes sense to me as a workaround. My (subjective perhaps) opinion is that regardless of which of the options is correct, `Tldr` is most incorrect, so picking a better option would be nice. `TL;DR` happens to appear in dictionaries: Oxford, Cambridge, Merriam Webster, dictionary.com, etc.

I agree - FAQ should also have the same treatment.

>I think architecturally, maybe this would be something to add when supporting multiple languages. If you really did want to add it, I think the right way to do so would be with a localization framework in mind; something like locale = en_US, and then we map to correct default titles for english, chinese, etc.

Useful, but probably unnecessary for this I suspect.

**Comment by tommilligan** [comment]
Those are both fair arguments. And I suppose titlecasing the directive was just to avoid adding another lookup, which is trivial. So yeah, maybe let's go for it after all, I think all we need is a lookup from directive to title (doesn't even have to be exhaustive, can fallback to the titlecase if no better option given.

**Comment by joshka** [comment]
I'll slap a PR together
