### ISSUE TITLE
additional-css UNIX style paths

### ISSUE THREAD

**Issue by carlocorradini** [tommilligan/mdbook-admonish#161]
UNIX style paths should always be used for `additional-css`.
When running `mdbook-admonish` on a `UNIX` system, the paths are (correctly) normalized:
*Before*:
```toml
additional-css = ['./path/to/mdbook-admonish.css']
```
*After*:
```toml
additional-css = ['./path/to/mdbook-admonish.css']
```
On a Windows system, `mdbook-admonish` causes the paths to be (inaccurately) normalized and duplicated:
*Before*:
```toml
additional-css = ['./path/to/mdbook-admonish.css']
```
*After*:
```toml
additional-css = ['./path/to/mdbook-admonish.css', '.\path\to\mdbook-admonish.css']
```

**Comment by tommilligan** [comment]
Closed by #163
