### ISSUE TITLE
Set collapsible default value per directive

### ISSUE THREAD

**Issue by yannickseurin** [tommilligan/mdbook-admonish#169]
Hi!

If I'm not mistaken, currently it seems that the default collapsible value must be set globally for all directives.

It would be great if it were possible to set this default value to true for specific directives only.

**Comment by tommilligan** [comment]
Thanks for the suggestion - I agree that most global options should be applicable per block style.

I think the appropriate way to configure this would be like the `custom` array in the `book.toml` file, except with a `collapsible` property: https://tommilligan.github.io/mdbook-admonish/#custom-blocks

I think one of:
- A new array of overrides for builtin directives
- Just use the existing `custom` block, and if you specify a built-in directive, it overrides the default value

would work fine.

**Comment by yannickseurin** [comment]
Closed with PR #174
