### ISSUE TITLE
Using other markdown or html in titles 

### ISSUE THREAD

**Issue by s00500** [tommilligan/mdbook-admonish#179]
Hi, awesome tool!

Question, is it possible to somehow use markdown or html formating within titles ?

EG

admonish tip title="Some New Structure `my_structure`"

Any way to achieve this currently ?

Greetings,

**Comment by s00500** [comment]
Sorry for the issue.... mostly this is solved by using tildes for outer fence as per documentation

https://tommilligan.github.io/mdbook-admonish/#nested-markdownhtml

What I can not make work though is using a html element with a class in there

```
~~~ admonish block title="Value <div class="advanced"></div>"
```

Maybe you know the correct escape ?

**Comment by tommilligan** [comment]
Hi, thanks for the report. I agree this is something that should be supported, but I can't get it to work immediately and the error message displayed on failure is not helpful.

I'll take a look and see if I can improve the error handling enough to work out what the correct syntax is, then let you know.

**Comment by s00500** [comment]
Awesome! thanks!

**Comment by tommilligan** [comment]
Hi, this should be fixed by #181

If you're able to, please install from git directly and see if it fixes your use case:

```
cargo install --git https://github.com/tommilligan/mdbook-admonish --branch main
```

I'll cut a 0.17.0 release with the fix after a few other things.

**Comment by tommilligan** [comment]
And sorry to clarify, for your HTML example this should render correctly on `main`:
````markdown
```admonish block title='With <div class="advanced">HTML</div>'
Body content
```
````

**Comment by s00500** [comment]
This is great, I have just tested it successfully! Thanks for the insanely fast fix
