### ISSUE TITLE
Code in admonish blocks?

### ISSUE THREAD

**Issue by matthiasbeyer** [tommilligan/mdbook-admonish#32]
Is it possible to have code blocks inside admonish blocks? Would be awesome for the "example" block type!

But I cannot think of a way that markup would look like... So maybe I'm just missing something...

**Comment by schungx** [comment]
Of course you can.

Make sure the adminish block uses `~~~` and the inner code block uses ```` ``` ````

Afaik it cannot be the other way round.

**Comment by matthiasbeyer** [comment]
Ah, awesome! Thanks for the fast reply!
