### ISSUE TITLE
mdbook without installation possible?

### ISSUE THREAD

**Issue by rufus42** [tommilligan/mdbook-admonish#46]
Hello Tom Milligan @tommilligan,

thank you very much for your great work.

Is there any way to use the exe file without `mdbook-admonish install`?
I can`t / am not allowed to install anything on my computer.

Thanks for your time and sorry for asking my question here, I didn`t find any forum or similar unfortunately.

Many greetings
rufus42

**Comment by schungx** [comment]
It appears that `mdbook` will spawn separate processes to run pre-processors... can you save a pre-built binary in your local folder, point your `PATH` to it, and then try?

If you can't even save files into your own folders, then how can you build the book?

**Comment by tommilligan** [comment]
Hi, thanks for your question. There are a couple of points that I think are being confused here:

- You can install the `mdbook-admonish` binary in a location that you control (i.e. doesn't require admin privileges). Here, "installation" is just saving a file in a specific location.
  - For example, `mkdir ./tmp && cargo install mdbook-admonish --root ./tmp` will compile `mdbook-admonish` and save it to `./tmp/bin/mdbook-admonish`
  - You could also just download the precompiled binary, available from the Github releases page
- `mdbook-admonish install` simply updates your mdbook's `book.toml`. Here, installation refer's to "installing" the configuration required for `mdbook-admonish` into your existing configuration.
- If you need to save the `mdbook-admonish` binary in a non-standard location (as above), to make your config work you will probably need to do one of:
  - In `book.toml`, change `command = "mdbook-admonish"` to `command = "./path/to/tmp/bin/mdbook-admonish"`
  - Update your `$PATH` to include the binary's location

I hope these steps are helpful for you - if you still have problems, please let me know:

- Specifically what step you are having problems with
- Any relevant commands you have run, and their output
- Your operating system and version of rust/mdbook/mdbook-admonish

**Comment by rufus42** [comment]
Hello Tom Milligan @tommilligan ,

many, many thanks for your response.
I was totally touched/excited by your detailed, beginner-friendly answer.

IT WORKS!

My point of misunderstanding:
I thought I had to have Rust installed to run `mdbook-admonish install`.
I guess I didn`t read carefully enough.
(English is not my mother tongue, my native language is German. I have my posts translated by DeepL.)

Thanks for your clear words, your plugin helps me.
And most of all: thanks for your work!

Many greetings
rufus42

Problem: solved

Translated with www.DeepL.com/Translator (free version)

**Comment by tommilligan** [comment]
Excellent, glad it's working for you! No problem at all, happy to help.

Closed as resolved.
