### ISSUE TITLE
The way to install it isn't specified.

### ISSUE THREAD

**Issue by blyxyas** [tommilligan/mdbook-admonish#56]
Hi, I found it hard to install it (This is my first mdbook), maybe there should be a  section talking about that?

```
cargo install mdbook-admonish
```
Then
```
mdbook-admonish install
```

Isn't something that a new user would know. I needed to check the source code of this repo to figure it out

**Comment by tommilligan** [comment]
Hi, thanks for using the project!

The way to install and use the plugin is specified in the readme: https://github.com/tommilligan/mdbook-admonish#installation

If you have any suggestions as to how this can be improved, please let me know.

**Comment by blyxyas** [comment]
You are right. I read the book without reading the `README.md` file. Sorry for wasting your time.

**Comment by tommilligan** [comment]
No worries! I wondered if that was the case - it's probably confusing that some of the content is duplicated but not all of it. I may move the content back to the book and just keep a link in the readme (maybe?)
