### ISSUE TITLE
setting to default to empty title

### ISSUE THREAD

**Issue by ShaunSHamilton** [tommilligan/mdbook-admonish#82]
Personally, I find myself adding `title=""` to almost every admonishment.

It would be nice to have a flag to default to no title:

```toml
[preprocessor.admonish]
default-empty-title = true
```

---

That being said, I would also like to keep the icons in the `::before`. I have tried spaces for titles, but get inconsistent styling for the colour -bar/strip:
<img width="83" alt="image" src="https://user-images.githubusercontent.com/51722130/232165150-1fd7abcc-adb4-4c2c-9628-7353cefb51ee.png">

I have found setting `title = "&#x200b;"` alleviates the styling issues.

---

Is this something `mdbook-admonish` would be interested in?

**Comment by tommilligan** [comment]
Hi, thanks for the suggestions!

It sounds like there are two distinct things here:

- Titles set to `" "` do not render properly (bug)
  - I suggest that the CSS styling is updated to give the top title bar an appropriate min-height; the bar to render properly independent of content.
- Users should be able to set a default value for the title (feature)
  - I think this should be a generic feature for all settings. We can start with just `title`, but being forwards compatible with e.g. `collapsible`
  - Agree that setting defaults in the book.toml file works. I would have this as a new table, like:
```toml
[preprocessor.admonish.default]
title = ""
```

---

I would be happy to review PRs tackling the above 🙂
