### ISSUE TITLE
I would like to see v1.9.0 released to crates.io as well.

### ISSUE THREAD

**Issue by CoralPink** [tommilligan/mdbook-admonish#97]
Hello!

As the title says, any plans to release v1.9.0 on crates.io?
I am eagerly waiting for it!

I love `mdbook-admonish` because it makes the site look great 😆

Thanks!

**Comment by tommilligan** [comment]
Hey, thanks for the ping. I didn't realise this hadn't happened automatically - will work on fixing CI so it does next time.

In the meantime, I've just done the release manually, sorry for the delay!

**Comment by CoralPink** [comment]
Thank you so much for your quick response!

I will use it as soon as possible! 🤗
